name: nomod CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: recursive                
    - name: apt-get
      run: |
         set -x
         sudo apt-get update
         sudo apt-get install git build-essential fakeroot libncurses5-dev libssl-dev ccache dfu-util u-boot-tools device-tree-compiler libssl-dev mtools bc python cpio zip unzip rsync file wget gcc-arm-linux-gnueabihf libiio-dev libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev build-essential bison flex libssl-dev bc
    - name: Cache
      uses: actions/cache@v2.1.7
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: plutosdr-fw/buildroot/dl/
        # An explicit key for restoring and saving the cache
        key: plutodl
        
    - name: configure buildroot
      run: |
         set -x
         cd plutosdr-fw
         export CROSS_COMPILE=arm-linux-gnueabihf-
         
         git tag v0.34 || true
         
         wget -N --quiet "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tar.xz"
         
         tar -xf gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tar.xz
         
         ls -al
                  
         export PATH=`pwd`/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf/bin:$PATH
         
         sed -i 's~BR2_TOOLCHAIN_EXTERNAL_HEADERS_4_14=y~BR2_TOOLCHAIN_EXTERNAL_HEADERS_4_18=y~' buildroot/configs/zynq_pluto_defconfig
                  
         which ${CROSS_COMPILE}gcc
         
         make
         
         cd buildroot
         make batctl 
         make bridge-utils 
         #rm -fr output/build/fftw-3.3.7/
         make fftw-double 
         make fftw-single 
         make iperf3 
         make iproute2 
         make liquid-dsp 
         make tunctl
         #rm -fr output/build/util-linux-2.31.1/
         make util-linux
         cd ..
         
         make
         
         cd ..
         # fix the compiler
         sed -i 's~arm-xilinx-linux-gnueabi-gcc~arm-linux-gnueabihf-gcc~' third_party/libtuntap/build_tun.sh
         sed -i 's~arm-xilinx-linux-gnueabi-ar~arm-linux-gnueabihf-ar~' third_party/libtuntap/build_tun.sh
         # fix the paths
         sed -i 's~../../../buildroot/output/host/arm-buildroot-linux-gnueabi/sysroot/~../../plutosdr-fw/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/~' third_party/libtuntap/build_tun.sh
         # fix the include order
         sed -i '1s~^~#include <net/ethernet.h>\n~' third_party/libtuntap/tuntap-unix-linux.c
         
         cd third_party/libtuntap && sh ./build_tun.sh && cd .. && cd ..
         
         make
         cp third_party/libfec/*.so ./plutosdr-fw/buildroot/output/target/usr/lib
         cp charon ./plutosdr-fw/buildroot/output/target/usr/bin
         cd plutosdr-fw
         make
         
         rm build/legal-info*

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: plutosdr-fw/build

